# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Штампы
email: info@nstmp.ru
description: >- # this means to ignore newlines until "baseurl:"
  Громко. Включай, ломай стереотипы
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.nstmp.ru # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Настройки группы
city: Москва
genre: Техно-панк

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Социальные сети
social:
  vk:
    url: https://vk.com/neurostamps
    icon: vk
  telegram:
    url: https://t.me/neurostamps
    icon: telegram
  youtube:
    url: https://youtube.com/neurostamps
    icon: youtube
  bandcamp:
    url: https://neurostamps.bandcamp.com
    icon: bandcamp

# Переменные
neuro_primary: "#0ff" # Неоновый циан
neuro_secondary: "#f0f" # Неоновый пурпур
neuro_dark: "#0a0a12" # Глубокий сине-черный
